apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      owner: frontend

  template:
    metadata:
      labels:
        owner: frontend

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

