apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    tier: frontend

spec:
  # modify replicas according to need
  replicas: 4
  selector:
    matchLabels:
      app: nginx-pod1
    
  template:
      metadata:
        labels:
          app: nginx-pod1
      spec:
        containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80

