# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  # Web Server
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.6"
    web.vm.provision "shell", path: "web.sh"

    # Set VirtualBox-specific settings for webserver
    web.vm.provider "virtualbox" do |vb|
      vb.name = "WEB"
      vb.memory = "1024"
    end
  end

  # DB Server
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.7"
    db.vm.provision "shell", path: "db.sh"

    # Set VirtualBox-specific settings for dbserver
    db.vm.provider "virtualbox" do |vb|
      vb.name = "DB"
      vb.memory = "1024"
    end
  end
end

