# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  config.vm.define "wordpress" do |wd|
    wd.vm.hostname = "wordpress"
    wd.vm.network "private_network", ip: "192.168.56.10"
    wd.vm.provision "shell", path: "wordpress_setup.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true  # Uncomment to show GUI
    vb.name = "wordpress_deploy"
    # vb.memory = "1024"  # Uncomment to set memory
  end
end

